# Generated by Django 5.2 on 2026-09-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_rate',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
